apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    app: nginx
    testsvc: {{ .Release.Namespace }}-ns
    revision: {{ .Release.Revision }}-revision
    kube-test-minor: "{{ .Capabilities.KubeVersion.Minor }}"
    kube-test-major: "{{ .Capabilities.KubeVersion.Major }}"
    Helm-test-minor: "{{ .Capabilities.KubeVersion.Minor }}"
    Helm-test-major: "{{ .Capabilities.HelmVersion.Version }}"
    chartversion: {{ .Chart.AppVersion }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Chart.Name }}
              containerPort: 80
              protocol: TCP